kind: pipeline
type: docker
name: build-and-push

steps:
  - name: docker
    image: plugins/docker
    settings:
      repo: ghcr.io/${DRONE_REPO_OWNER}/rustclaw
      registry: ghcr.io
      username:
        from_secret: ghcr_username
      password:
        from_secret: ghcr_token
      tags:
        - ${DRONE_TAG}
        - ${DRONE_TAG##v}
        - ${DRONE_TAG%%.*}
        - ${DRONE_TAG%%.*}.${DRONE_TAG#*.}
        - latest
      auto_tag: false
      daemon_off: false
      platforms:
        - linux/amd64
        - linux/arm64
      build_args:
        - BUILDKIT_INLINE_CACHE=1
      cache_from:
        - ghcr.io/${DRONE_REPO_OWNER}/rustclaw:latest

trigger:
  event:
    - tag
  ref:
    - refs/tags/v*