kind: pipeline
type: docker
name: build-and-push

steps:
  - name: docker
    image: thegeeklab/drone-docker-buildx:24
    privileged: true
    settings:
      repo: ghcr.io/${DRONE_REPO_OWNER}/rustclaw
      registry: ghcr.io
      username:
        from_secret: ghcr_username
      password:
        from_secret: ghcr_token
      tags:
        - ${DRONE_TAG}
        - ${DRONE_TAG##v}
        - ${DRONE_TAG%%.*}
        - ${DRONE_TAG%%.*}.${DRONE_TAG#*.}
        - latest
      platforms:
        - linux/amd64
        - linux/arm64
      buildkit_cache:
        type: registry
        ref: ghcr.io/${DRONE_REPO_OWNER}/rustclaw:buildcache
        mode: max

trigger:
  event:
    - tag
  ref:
    - refs/tags/v*