kind: pipeline
type: docker
name: build-and-push

steps:
  - name: build-and-push
    image: thegeeklab/drone-docker-buildx
    privileged: true
    settings:
      repo: ghcr.io/${DRONE_REPO_OWNER}/rustclaw
      registry: ghcr.io
      tags:
        - ${DRONE_TAG}
        - latest
      username:
        from_secret: ghcr_username
      password:
        from_secret: ghcr_token
      cache_from:
        - type=registry,ref=ghcr.io/${DRONE_REPO_OWNER}/rustclaw:cache
      cache_to:
        - type=registry,ref=ghcr.io/${DRONE_REPO_OWNER}/rustclaw:cache,mode=max

trigger:
  event:
    - tag
  ref:
    - refs/tags/v*